project_id: '542764'
api_token: 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
base_path: /
preserve_hierarchy: 1
base_url: 'https://api.crowdin.com'
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
