project_id: '542776'
api_token: ec0f76e22bfa78f9654cc13b840ad4c31ba1af83d1818af392413b4bcfeb001f93514a5b27e74314
base_path: /
preserve_hierarchy: 1
base_url: 'https://api.crowdin.com'
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
