"project_id": "542776"
"api_token": "537d70270d841ff3730108f3ea0389957711a75fc924341f16ee12420dcc5fde2d53e58570c9fde5"
"base_path": "/"
"preserve_hierarchy": true
"base_url": "https://api.crowdin.com"

"files": [
  {
    "source": "**/values/strings.xml",                                       #source files filter
    "translation": "/values-%two_letters_code%/%original_file_name%"         #where translations are stored
  }
]

#files:
#  - source: **/values/strings.xml
#    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
