project_id: '543878'
api_token: 54a98145e262dffc2ad5ab22d623e42ec69e067765425e900102af64c54e5849ac293fa14d1c48a0
base_path: /
preserve_hierarchy: 1
base_url: 'https://api.crowdin.com'
files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
